### ISSUE TITLE
Login to WsSecurity with pem cert

### ISSUE THREAD

**Issue by jakubLW** [WsdlToPhp/WsSecurity#10]
Hey it's possible to login to ws security with .pem certificate instead of username and password ?

**Comment by mikaelcom** [comment]
Maybe you just need to use the feature already available within the [SoapClient](https://www.php.net/manual/en/soapclient.soapclient.php) class using the option local_cert: **For HTTPS client certificate authentication use _local_cert_ and _passphrase_ options. An authentication may be supplied in the _authentication_ option. The authentication method may be either SOAP_AUTHENTICATION_BASIC (default) or SOAP_AUTHENTICATION_DIGEST.**

Let me know otherwise

**Comment by mikaelcom** [comment]
feel free to re-open if necessary
